server:
  port: 8083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-passenger-user
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0


